// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bukhavtsov/toolkit-log-service/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_381308df52732eb6, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

func init() {
	proto.RegisterFile("github.com/bukhavtsov/toolkit-log-service/pkg/pb/service.proto", fileDescriptor_381308df52732eb6)
}

var fileDescriptor_381308df52732eb6 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0xb5, 0x17, 0x8b, 0xb9, 0x88, 0x7b, 0x90, 0x65, 0xf5, 0x20, 0x3d, 0x09, 0xba, 0x19, 0xb0,
	0x78, 0x2a, 0x88, 0x08, 0xe2, 0xc5, 0x53, 0xfd, 0x38, 0x78, 0x4b, 0xd6, 0x69, 0x1a, 0x76, 0x9b,
	0x09, 0x9b, 0xd9, 0x95, 0xfe, 0x7b, 0x71, 0x93, 0x85, 0x62, 0x4f, 0xbd, 0xe5, 0xcd, 0xbc, 0xbc,
	0x37, 0xef, 0x89, 0x07, 0x63, 0x79, 0xdd, 0x69, 0x59, 0xd1, 0x06, 0x74, 0x57, 0xaf, 0x55, 0xcf,
	0x81, 0x7a, 0x60, 0xa2, 0xa6, 0xb6, 0x5c, 0x36, 0x64, 0xca, 0x80, 0x6d, 0x6f, 0x2b, 0x04, 0x5f,
	0x1b, 0xf0, 0x1a, 0x12, 0x94, 0xbe, 0x25, 0xa6, 0x6c, 0x9a, 0x60, 0x71, 0x61, 0x88, 0x4c, 0x83,
	0x30, 0x8c, 0x75, 0xb7, 0x02, 0xdc, 0x78, 0xde, 0x46, 0x56, 0x71, 0x99, 0x96, 0xca, 0x5b, 0x50,
	0xce, 0x11, 0x2b, 0xb6, 0xe4, 0x42, 0xda, 0x2e, 0x76, 0x6e, 0x68, 0xb6, 0x2b, 0x8e, 0x1a, 0x55,
	0x69, 0xd0, 0x95, 0xbd, 0x6a, 0xec, 0xb7, 0x62, 0x84, 0xbd, 0x47, 0xfa, 0x7c, 0xbb, 0x43, 0x0e,
	0x3f, 0xca, 0x18, 0x6c, 0x81, 0xfc, 0x20, 0xbf, 0x6f, 0x35, 0xbb, 0x11, 0xa7, 0x9f, 0xd8, 0x06,
	0x4b, 0x6e, 0x89, 0xc1, 0x93, 0x0b, 0x98, 0xe5, 0x62, 0xda, 0xc7, 0x51, 0x3e, 0xb9, 0x9a, 0x5c,
	0x9f, 0x2c, 0x47, 0x78, 0xf7, 0x21, 0xce, 0xde, 0x63, 0x0f, 0xaf, 0x64, 0xde, 0x62, 0xce, 0xec,
	0x51, 0x88, 0x17, 0xe4, 0x24, 0x92, 0x9d, 0xcb, 0x98, 0x4c, 0x8e, 0xb1, 0xe5, 0xf3, 0x5f, 0xec,
	0x22, 0x97, 0x63, 0x4d, 0xff, 0xec, 0x66, 0x47, 0x4f, 0xf7, 0x5f, 0xf3, 0x43, 0x4b, 0x5f, 0x78,
	0xad, 0x8f, 0x07, 0x8b, 0xf9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x24, 0x33, 0x7c, 0xb2,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToolkitLogServiceClient is the client API for ToolkitLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToolkitLogServiceClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type toolkitLogServiceClient struct {
	cc *grpc.ClientConn
}

func NewToolkitLogServiceClient(cc *grpc.ClientConn) ToolkitLogServiceClient {
	return &toolkitLogServiceClient{cc}
}

func (c *toolkitLogServiceClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.ToolkitLogService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolkitLogServiceServer is the server API for ToolkitLogService service.
type ToolkitLogServiceServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterToolkitLogServiceServer(s *grpc.Server, srv ToolkitLogServiceServer) {
	s.RegisterService(&_ToolkitLogService_serviceDesc, srv)
}

func _ToolkitLogService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolkitLogServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ToolkitLogService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolkitLogServiceServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToolkitLogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.ToolkitLogService",
	HandlerType: (*ToolkitLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _ToolkitLogService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/bukhavtsov/toolkit-log-service/pkg/pb/service.proto",
}
